export const DEFAULT_EXERCISES = [
  // Peito (15)
  { name: "Supino Reto",               category: "Peito" },
  { name: "Supino Inclinado",          category: "Peito" },
  { name: "Supino Declinado",          category: "Peito" },
  { name: "Supino Halteres",           category: "Peito" },
  { name: "Supino Inclinado Halteres", category: "Peito" },
  { name: "Supino Máquina",            category: "Peito" },
  { name: "Supino Pegada Neutra",      category: "Peito" },
  { name: "Crucifixo",                 category: "Peito" },
  { name: "Crucifixo Inclinado",       category: "Peito" },
  { name: "Crossover",                 category: "Peito" },
  { name: "Peck Deck",                 category: "Peito" },
  { name: "Voador Máquina",            category: "Peito" },
  { name: "Pullover",                  category: "Peito" },
  { name: "Flexão",                    category: "Peito" },
  { name: "Supino Pegada Fechada",     category: "Peito" },

  // Costas (15)
  { name: "Puxador Frontal",           category: "Costas" },
  { name: "Puxador Fechado",           category: "Costas" },
  { name: "Puxador Triângulo",         category: "Costas" },
  { name: "Puxador Unilateral",        category: "Costas" },
  { name: "Barra Fixa",                category: "Costas" },
  { name: "Remada T Bar",              category: "Costas" },
  { name: "Remada Alta",               category: "Costas" },
  { name: "Remada Curvado",            category: "Costas" },
  { name: "Remada Sentado Máquina",    category: "Costas" },
  { name: "Remada Unilateral",         category: "Costas" },
  { name: "Remada Fechada",            category: "Costas" },
  { name: "Serrote",                   category: "Costas" },
  { name: "Levantamento Terra",        category: "Costas" },
  { name: "Hiperextensão Lombar",      category: "Costas" },
  { name: "Good Morning",              category: "Costas" },

  // Ombro (15)
  { name: "Desenvolvimento Barra",     category: "Ombro" },
  { name: "Desenvolvimento Halteres",  category: "Ombro" },
  { name: "Desenvolvimento Máquina",   category: "Ombro" },
  { name: "Desenvolvimento Arnold",    category: "Ombro" },
  { name: "Frontal Ombro",             category: "Ombro" },
  { name: "Lateral Ombro",             category: "Ombro" },
  { name: "Elevação Lateral Cabo",     category: "Ombro" },
  { name: "Posterior de Ombro",        category: "Ombro" },
  { name: "Peck Deck Posterior",       category: "Ombro" },
  { name: "Crucifixo Invertido",       category: "Ombro" },
  { name: "Face Pull",                 category: "Ombro" },
  { name: "Remada Alta Ombro",         category: "Ombro" },
  { name: "Encolhimento Barra",        category: "Ombro" },
  { name: "Encolhimento Halteres",     category: "Ombro" },
  { name: "Lateral Inclinado",         category: "Ombro" },

  // Bíceps (15)
  { name: "Rosca Direta",              category: "Bíceps" },
  { name: "Rosca Alternada",           category: "Bíceps" },
  { name: "Rosca Martelo",             category: "Bíceps" },
  { name: "Rosca Concentrada",         category: "Bíceps" },
  { name: "Rosca Barra W",             category: "Bíceps" },
  { name: "Bíceps Scott Alta",         category: "Bíceps" },
  { name: "Rosca Máquina",             category: "Bíceps" },
  { name: "Rosca Cabo",                category: "Bíceps" },
  { name: "Rosca Polia",               category: "Bíceps" },
  { name: "Rosca Inclinada",           category: "Bíceps" },
  { name: "Rosca Spider",              category: "Bíceps" },
  { name: "Rosca Inversa",             category: "Bíceps" },
  { name: "Rosca Simultânea",          category: "Bíceps" },
  { name: "Rosca 21",                  category: "Bíceps" },
  { name: "Rosca Cross",               category: "Bíceps" },

  // Tríceps (15)
  { name: "Tríceps Barra W",           category: "Tríceps" },
  { name: "Tríceps Polia",             category: "Tríceps" },
  { name: "Tríceps Corda",             category: "Tríceps" },
  { name: "Tríceps Barra Reta",        category: "Tríceps" },
  { name: "Tríceps Máquina",           category: "Tríceps" },
  { name: "Tríceps Francês",           category: "Tríceps" },
  { name: "Tríceps Testa",             category: "Tríceps" },
  { name: "Tríceps Overhead",          category: "Tríceps" },
  { name: "Extensão Unilateral",       category: "Tríceps" },
  { name: "Tríceps Banco",             category: "Tríceps" },
  { name: "Mergulho",                  category: "Tríceps" },
  { name: "Kickback",                  category: "Tríceps" },
  { name: "Coice Cabo",                category: "Tríceps" },
  { name: "Tríceps Supino Fechado",    category: "Tríceps" },
  { name: "Tríceps JM Press",          category: "Tríceps" },

  // Perna (15)
  { name: "Agachamento Livre",         category: "Perna" },
  { name: "Agachamento Hack",          category: "Perna" },
  { name: "Agachamento Sumô",          category: "Perna" },
  { name: "Agachamento Búlgaro",       category: "Perna" },
  { name: "Leg Press",                 category: "Perna" },
  { name: "Leg Press 45°",             category: "Perna" },
  { name: "Extensora",                 category: "Perna" },
  { name: "Cadeira Flexora",           category: "Perna" },
  { name: "Flexora em Pé",             category: "Perna" },
  { name: "Stiff",                     category: "Perna" },
  { name: "Afundo",                    category: "Perna" },
  { name: "Adutora",                   category: "Perna" },
  { name: "Abdutora",                  category: "Perna" },
  { name: "Panturrilha Sentado",       category: "Perna" },
  { name: "Panturrilha em Pé",         category: "Perna" },

  // Glúteo (15)
  { name: "Hip Thrust",                category: "Glúteo" },
  { name: "Hip Thrust Haltere",        category: "Glúteo" },
  { name: "Ponte Glúteo",              category: "Glúteo" },
  { name: "Glúteo Máquina",            category: "Glúteo" },
  { name: "Donkey Kick",               category: "Glúteo" },
  { name: "Coice Perna Cabo",          category: "Glúteo" },
  { name: "Extensão Quadril",          category: "Glúteo" },
  { name: "Abdução em Pé Cabo",        category: "Glúteo" },
  { name: "Step Up",                   category: "Glúteo" },
  { name: "Agachamento Sumô Glúteo",   category: "Glúteo" },
  { name: "Passada Lateral",           category: "Glúteo" },
  { name: "Afundo Reverso",            category: "Glúteo" },
  { name: "Elevação Quadril Unilateral", category: "Glúteo" },
  { name: "Abdutora Máquina",          category: "Glúteo" },
  { name: "Agachamento Búlgaro Glúteo", category: "Glúteo" },

  // Abdômen (15)
  { name: "Abdominal Crunches",        category: "Abdômen" },
  { name: "Abdominal Máquina",         category: "Abdômen" },
  { name: "Abdominal Remador",         category: "Abdômen" },
  { name: "Abdominal Oblíquo",         category: "Abdômen" },
  { name: "Prancha",                   category: "Abdômen" },
  { name: "Elevação de Pernas",        category: "Abdômen" },
  { name: "Joelho ao Peito",           category: "Abdômen" },
  { name: "Russian Twist",             category: "Abdômen" },
  { name: "Roda Abdominal",            category: "Abdômen" },
  { name: "Crunch Polia",              category: "Abdômen" },
  { name: "Mountain Climber",          category: "Abdômen" },
  { name: "Hollow Body",               category: "Abdômen" },
  { name: "Abdominal V",               category: "Abdômen" },
  { name: "Vacuum",                    category: "Abdômen" },
  { name: "Dragon Flag",               category: "Abdômen" },

  // Cardio (15)
  { name: "Esteira",                   category: "Cardio" },
  { name: "Bicicleta Ergométrica",     category: "Cardio" },
  { name: "Elíptico",                  category: "Cardio" },
  { name: "Remo Ergométrico",          category: "Cardio" },
  { name: "Corda Naval",               category: "Cardio" },
  { name: "Pular Corda",               category: "Cardio" },
  { name: "Burpee",                    category: "Cardio" },
  { name: "Jumping Jack",              category: "Cardio" },
  { name: "Sprint",                    category: "Cardio" },
  { name: "Step Machine",              category: "Cardio" },
  { name: "Box Jump",                  category: "Cardio" },
  { name: "Kettlebell Swing",          category: "Cardio" },
  { name: "Skipping",                  category: "Cardio" },
  { name: "Corrida HIIT",              category: "Cardio" },
  { name: "Escada",                    category: "Cardio" },
];

export async function createDefaultExercises(userId, prisma) {
  const existing = await prisma.machine.findMany({ where: { userId }, select: { name: true } });
  const existingNames = new Set(existing.map((m) => m.name));
  const toCreate = DEFAULT_EXERCISES.filter((e) => !existingNames.has(e.name));
  if (toCreate.length === 0) return;
  await prisma.machine.createMany({
    data: toCreate.map((e) => ({ userId, name: e.name, category: e.category })),
  });
}
